### ISSUE TITLE
Can't seem to use?

### ISSUE THREAD

**Issue by Anahkiasen** [chenglou/upgrade-reason-react#1] opened 2018-08-07 17:03 UTC
Not sure if I'm doing anything wrong but I can't seem to use this, as the postinstall script keeps failing on this:

```
FAILED: src/migrate.cmo src/migrate.cmi
./node_modules/upgrade-reason-react/node_modules/bs-platform/vendor/ocaml/ocamlc.opt  -bs-super-errors  -I ./node_modules/upgrade-reason-react/node_modules/bs-platform/vendor/ocaml/lib/ocaml -I src   -I ./node_modules/upgrade-reason-react/node_modules/bs-platform/vendor/ocaml/lib/ocaml/compiler-libs  -no-alias-deps   -color   always -o src/migrate.cmo -w -30-40+6+7+27+32..39+44+45+101-40-20-21-26-27-28-32-45-44-33-37-34-39-6 -g -c -intf-suffix .mliast_simple -impl src/migrate.mlast_simple

  We've found a bug for you!
  ./node_modules/upgrade-reason-react/src/migrate.re 1:6-9

  1 │ open Belt;
  2 │
  3 │ open Refmt_api.Migrate_parsetree;

  The module or file Belt can't be found.
```

Which I'm not sure I understand since Belt is, well, Belt. I've tried both with Yarn and NPM, all my dependencies are up to date (reason-react, bs-platform, etc.). Is there anything I might have missed?

**Comment by pewniak747** [comment] 2018-08-08 14:19
@Anahkiasen @chenglou I'm experiencing this issue as well. I think the cause might be an old version of `bs-platform` specified in package.json, the one that does not contain `Belt`.

I was able to perform the upgrade by doing the following:

Clone the script:
```
git clone https://github.com/chenglou/upgrade-reason-react
cd upgrade-reason-react
```

Update the bs-platform version:
```diff
   },
   "homepage": "https://github.com/chenglou/upgrade-reason-react-to-031#readme",
   "dependencies": {
-    "bs-platform": "github:bsansouci/bsb-native#2.1.1"
+    "bs-platform": "github:bsansouci/bsb-native#3.2.0"
   }
 }
```

Install deps:
```
npm install
```

Perform the upgrade of my files:

```
cd ..
upgrade-reason-react/lib/bs/bytecode/migrate.byte src/**/*.re
```

**Comment by chenglou** [comment] 2018-08-09 03:49
Crap, such a failure on my part, sorry about that. This is fixed now.

Thanks for the report!

**Closed as completed by chenglou** 2018-08-09 03:49 UTC

**Comment by pewniak747** [comment] 2018-08-09 12:46
@chenglou Could you also update the `0.4.2-to-0.5.0` tag to point to the current master, so that people installing `npm install https://github.com/chenglou/upgrade-reason-react\#0.4.2-to-0.5.0` can get the fix?

**Comment by chenglou** [comment] 2018-08-09 17:34
Good point, done
